// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJBxk5u4W2OKVzU26cl5rptFgOHjoQdng',
    appId: '1:32799937812:web:4810352a234a2a90195e01',
    messagingSenderId: '32799937812',
    projectId: 'celular-376f9',
    authDomain: 'celular-376f9.firebaseapp.com',
    storageBucket: 'celular-376f9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNHJM8eHPNWqlX17upo7ERZskeC_WB704',
    appId: '1:32799937812:android:e1f85f458c8042a8195e01',
    messagingSenderId: '32799937812',
    projectId: 'celular-376f9',
    storageBucket: 'celular-376f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt00AFmsaKwUwf6CRSNQ9bmgir6f5FxM4',
    appId: '1:32799937812:ios:c72eebd62ae6c5df195e01',
    messagingSenderId: '32799937812',
    projectId: 'celular-376f9',
    storageBucket: 'celular-376f9.firebasestorage.app',
    iosBundleId: 'com.example.celularDetectorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt00AFmsaKwUwf6CRSNQ9bmgir6f5FxM4',
    appId: '1:32799937812:ios:c72eebd62ae6c5df195e01',
    messagingSenderId: '32799937812',
    projectId: 'celular-376f9',
    storageBucket: 'celular-376f9.firebasestorage.app',
    iosBundleId: 'com.example.celularDetectorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJBxk5u4W2OKVzU26cl5rptFgOHjoQdng',
    appId: '1:32799937812:web:d2a50bac0ad94ff9195e01',
    messagingSenderId: '32799937812',
    projectId: 'celular-376f9',
    authDomain: 'celular-376f9.firebaseapp.com',
    storageBucket: 'celular-376f9.firebasestorage.app',
  );
}
